version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume-data:/var/lib/rabbitmq
      - rabbitmq-volume-log:/var/log/rabbitmq
  rabbitmqproducer:
    container_name: RabbitMQProducer
    build: 
      context: .
      dockerfile: ProducerDockerFile
    environment: 
      - QuequeName=slhkl
      - RabbitMQUri=amqp://root:root@rabbitmq:5672
    ports: 
      - "80:80"
  rabbitmqconsumer:
    container_name: rabbitmqconsumer
    build:
      context: .
      dockerfile: ConsumerDockerFile
    environment: 
      - QuequeName=slhkl
      - RabbitMQUri=amqp://root:root@rabbitmq:5672
volumes:
  rabbitmq-volume-data:
  rabbitmq-volume-log: