version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume-data:/var/lib/rabbitmq
      - rabbitmq-volume-log:/var/log/rabbitmq
    deploy:
      replicas: 1
  rabbitmqproducer:
    image: salihkol/rabbitmq_producer
    environment:
      - QuequeName=slhkl
      - RabbitMQUri=amqp://root:root@rabbitmq:5672
    ports:
      - 80:80
    deploy:
      replicas: 1
  rabbitmqconsumer:
    image: salihkol/rabbitmq_consumer
    environment:
      - QuequeName=slhkl
      - RabbitMQUri=amqp://root:root@rabbitmq:5672
    deploy:
      replicas: 0
volumes:
  rabbitmq-volume-data:
  rabbitmq-volume-log:        